version: '3.7'

services:
  mdgt_dashboard:
    build: ./
    container_name: mdgt_dashboard
    ports:
      - 8000:8000
    restart: always
    volumes:
      - /home/nick/projects/reports:/files

volumes:
  files: