version: '3.7'

services:
  service_organization:
    build: ./service_organization/
    container_name: service_organization
    ports:
      - 8000:8000
    restart: always
    volumes:
      - /home/user_bot/disk-z:/files
      - /home/user_bot/database/:/database

  web:
    build: ./service_front/
    container_name: web
    ports:
      - 80:80
    restart: always

  service_customers:
    build: ./service_customers/
    container_name: service_customers
    ports:
      - 9000:9000
    restart: always
    volumes:
      - /home/nick/database/:/database

  service_bot:
    build: ./service_bot
    container_name: service_bot
    restart: always
    network_mode: host

volumes:
  files:
