version: '3.7'

services:
  mdgt_dashboard:
    build: ./
    container_name: mdgt_dashboard
    ports:
      - 8000:8000
    restart: always
    volumes:
      - /home/nick/projects/reports:/files

  web:
    build: ./front/
    container_name: web
    ports:
      - 80:80
    restart: always

  bot:
    build: ./bot
    container_name: bot
    restart: always
    network_mode: host

volumes:
  files:
